### ISSUE TITLE
"docker-compose up" is broken

### ISSUE THREAD

**Issue by josh-padnick** [kbariotis/gruntwork-io.github.io#17]
Hi @kbariotis,

When I run `docker-compose up`, I receive the following error. Is this something you can fix?

```
josh@Joshs-MacBook-Pro-2 ~/c/gruntwork-io.github.io (fix-gem)> docker-compose up
Starting gruntworkiogithubio_web_1
Attaching to gruntworkiogithubio_web_1
web_1  | /usr/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/spec_set.rb:94:in `block in materialize': Could not find i18n-0.8.1 in any of the sources (Bundler::GemNotFound)
web_1  | 	from /usr/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/spec_set.rb:87:in `map!'
web_1  | 	from /usr/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/spec_set.rb:87:in `materialize'
web_1  | 	from /usr/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/definition.rb:137:in `specs'
web_1  | 	from /usr/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/definition.rb:182:in `specs_for'
web_1  | 	from /usr/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/definition.rb:171:in `requested_specs'
web_1  | 	from /usr/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/environment.rb:18:in `requested_specs'
web_1  | 	from /usr/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:13:in `setup'
web_1  | 	from /usr/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler.rb:92:in `setup'
web_1  | 	from /usr/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/setup.rb:18:in `<top (required)>'
web_1  | 	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
web_1  | 	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
gruntworkiogithubio_web_1 exited with code 1
```

Thanks!

**Comment by kbariotis** [comment]
@josh-padnick Will you please try the following `docker-compose.yml` file?

```
web:
  image: jekyll/jekyll:pages
  command: jekyll serve --drafts --incremental --host 0.0.0.0
  volumes:
    - .:/srv/jekyll
  ports:
    - "4000:4000"
```

The above will use the official Jekyll image. See I am assuming that the current [`Dockerfile`](https://github.com/kbariotis/gruntwork-io.github.io/blob/master/Dockerfile) and the [Gruntwork docker image](https://hub.docker.com/r/gruntwork/gruntwork-io/) are quite old and since I have updated the `github-pages` gem is having some sort of conflicts. My Ruby/Bundler knowledge is limited, though, I could be wrong.

Since there is no need for a custom Docker installation, the above will serve us just right.

**Comment by josh-padnick** [comment]
Your updated `docker-compose.yml` worked for me!

**Comment by josh-padnick** [comment]
I'm not sure how stable the `pages` tag is for the `jekyll` docker image, so I also tried with `jekyll:3.4.0` and this worked as well. Given the two, I'm guessing I'd prefer the tag that explicitly gives us a version since this is unlikely to change?

**Comment by kbariotis** [comment]
Absolutely Josh! Will commit to master.
